version: '3'
services:

  postgres_db:
    image: postgres:15-alpine
    container_name: postgres_db
    env_file:
      - envs/common.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-databases:/docker-entrypoint-initdb.d
    networks:
      - movies-network
    ports:
      - "5432:5432"
    expose:
      - "5432"

  nginx:
    image: nginx:1.19.2
    container_name: "nginx"
    volumes:
      - ./configs/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./configs/nginx/conf.d:/etc/nginx/conf.d:ro
    depends_on:
      - auth_service
      - jaeger
    networks:
      - movies-network
    ports:
      - "80:80"

  auth_service:
    image: "auth_service"
    build: ./auth_service
    container_name: auth_service
    networks:
      - movies-network
    depends_on:
      - postgres_db
    env_file:
      - envs/common.env
    ports:
      - "8002:8002"
    expose:
      - "8002"

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    env_file:
      - envs/common.env
    networks:
      - movies-network
    ports:
      - "6831:6831/udp"
      - "16686:16686"

networks:
  movies-network:
    driver: bridge

volumes:
  postgres_data:
