x-common:
  &common
    networks:
      - custom


services:

  kino_db:
    <<: *common
    image: postgres:13.4
    container_name: "kino_db"
    env_file:
      - envs/common.env
    # environment:
    #   POSTGRES_DB: ${KINO_DB_NAME}
    #   POSTGRES_USER: ${KINO_DB_USER}
    #   POSTGRES_PASSWORD: ${KINO_DB_PASSWORD}
    volumes:
      - kino_postgres_data:/var/lib/postgresql/data
      - ./init-databases-cinema:/docker-entrypoint-initdb.d

  kino_service:
    <<: *common
    image: "kino_service"
    build: ./cinema_together
    container_name: cinema_together
    depends_on:
      - kino_db
    env_file:
      - envs/common.env
    expose:
      - "8005"

  postgres_db:
    <<: *common
    image: postgres:13.4
    container_name: postgres_db
    env_file:
      - envs/common.env
    volumes:
      - auth_postgres_data:/var/lib/postgresql/data
      - ./init-databases:/docker-entrypoint-initdb.d
    expose:
      - "5432"

  nginx:
    <<: *common
    image: nginx:1.19.2
    container_name: "nginx"
    volumes:
      - ./configs/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./configs/nginx/conf.d:/etc/nginx/conf.d:ro
    depends_on:
      - auth_service
      - jaeger
    ports:
      - "80:80"

  auth_service:
    <<: *common
    image: "auth_service"
    build: ./auth_service
    container_name: auth_service
    depends_on:
      - postgres_db
    env_file:
      - envs/common.env
    expose:
      - "8002"

  jaeger:
    <<: *common
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    env_file:
      - envs/common.env
    ports:
      - "6831:6831/udp"
      - "16686:16686"

  redis:
    <<: *common
    image: redis:7.2
    container_name: redis
    restart: always
    expose:
      - "6379"

networks:
  custom:
    name: custom

volumes:
  kino_postgres_data:
  auth_postgres_data:
