#!/bin/bash
set -e

psql --username postgres --dbname postgres <<-EOSQL
    CREATE USER $DB_USER;
    CREATE DATABASE $DB_NAME;
    ALTER DATABASE $DB_NAME OWNER TO $DB_USER;
    GRANT ALL PRIVILEGES ON DATABASE $DB_NAME TO $DB_USER;
    GRANT ALL ON SCHEMA public TO $DB_USER;

    CREATE USER $AUTH_DB_USER;
    CREATE DATABASE $AUTH_DB_NAME;
    ALTER DATABASE $AUTH_DB_NAME OWNER TO $AUTH_DB_USER;
    GRANT ALL PRIVILEGES ON DATABASE $AUTH_DB_NAME TO $AUTH_DB_USER;
    GRANT ALL ON SCHEMA public TO $AUTH_DB_USER;
EOSQL